name: CI

on:
  push:
    branches:
      - master
      - v9.0
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    strategy:
      matrix:
        rocq_version:
          - 'dev'
          - '9.0.1'
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: rocq-community/docker-coq-action@v1
        with:
          opam_file: 'rocq-relation-algebra.opam'
          coq_version: ${{ matrix.rocq_version }}

# See also:
# https://github.com/rocq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
